---
- name: Check AV Service
  hosts: all
  gather_facts: true
  connection: winrm
  tasks:
  - name: Check Cylance is Running
    win_service:
     name: CylanceSvc
     start_mode: auto
     state: started
