---
- hosts: localhost
  vars:
    job_id: "{{ lookup('env', 'JOB_ID') }}"
  tasks:
    - name: Get the previous job in the current workflow
      tower_previous_workflow_job:
        tower_base_url: 'https://10.100.17.235'
        tower_password: password
        tower_username: admin
        tower_job_id: "{{ job_id }}"
      register: previous_job
    - name: Beautify output
      beautify_ansible_job_output:
        tower_base_url: 'https://10.100.17.235'
        tower_password: password
        tower_username: admin
        tower_job_id: "{{ previous_job.job_id }}"
      register: job
    - name: Prepare the report
      win_template:
        src: html-report.j2
        dest: "\\10.100.0.171\\www\\report.html"
