---
- hosts: all
  tasks:
    - name: Ensure IIS is enabled
      win_feature:
        name: Web-Server
        state: present
        become: yes
    - name: Ensure that there is no binding on HTTP port
      win_iis_webbinding:
        name: Default Web Site
        port: 80
        state: absent
        become: yes
      when: sn_u_http_exception == "false"
    - name: Ensure that there is the binding on HTTPS port
      win_iis_webbinding:
        name: Default Web Site
        protocol: https
        port: 443
        certificate_store_name: 
        certificate_hash: 5728220c537f92754c5ea4e70035fcdb4b0e58e2
        state: present
        become: yes
      when: sn_u_http_exception == "false"
    - name: Ensure that there is the binding on HTTP port
      win_iis_webbinding:
        name: Default Web Site
        port: 80
        state: present
        become: yes
      when: sn_u_http_exception == "true"
    - name: Ensure that there is no binding on HTTPS port
      win_iis_webbinding:
        name: Default Web Site
        protocol: https
        port: 443
        certificate_hash: 5728220c537f92754c5ea4e70035fcdb4b0e58e2
        state: absent
        become: yes
      when: sn_u_http_exception == "true"

